#!/usr/bin/env bash

__all_files_in () {
  find "$DOTFILES_HOME/$1" -type f -and -name "*.$1"
}

__load_all_files_in () {
  for file in `__all_files_in $1`; do
    source $file
  done
}

__display_alias () {
  __all_files_in "alias/$2" |
    xargs cat |
    grep "alias" --color=never
}

dotfiles () { 
  case $1 in
    load)
      __load_all_files_in 'alias'
      __load_all_files_in 'completion'
      __load_all_files_in 'functions'
      __load_all_files_in 'plugin'
      __load_all_files_in 'private'
      __load_all_files_in 'theme'
    ;;
    update)	
      (cd $DOTFILES_HOME; git pull --rebase)
      dotfiles load
    ;;
    aliases)
      __display_alias $2
    ;;
    tree)
      tree "$DOTFILES_HOME/$2"
    ;;
    *)
      echo "Command not found"
  esac
}
