#!/usr/bin/env bash

__all_files_in () {
  find "$DOTFILES_HOME/$1" -type f -and -name "*.$1"
}

__load_all_files_in () {
  for file in `__all_files_in $1`; do
    source $file
  done
}

__display_alias () {
  __all_files_in "alias" |
    xargs cat |
    grep "alias" --color=never
}

__update_dotfiles () {
  (cd $DOTFILES_HOME; git pull --rebase)
  source "$DOTFILES_HOME/init"
}

__load_dotfiles () {
  for dir in 'alias' 'links' 'functions' 'options'; do
    __load_all_files_in $dir
  done
}

__print_dotfiles_usage () {
cat <<EOF
Usage: dotfiles <command>
Commands:
  lodad    Load/reload all dotfiles
  update   Update dotfiles from github
  aliases  Show all alias or alias in the file specified
EOF
}

dotfiles () {
  case $1 in
    load) __load_dotfiles;;
  update) __update_dotfiles;;
 aliases) __display_alias;;
    help) __print_dotfiles_usage;;
       *) __print_dotfiles_usage
  esac
}
